name: Release

on:
  release:
    types: [released]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
        with:
          python-version: "3.9"
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - run: uv run --with build python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - uses: svenstaro/upload-release-action@2.3.0
        with:
          file: dist/*
          file_glob: true

  qgis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
        with:
          python-version: "3.9"
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      # Use --no-editable so .dist-info is written to site-packages instead of .egg-info
      - run: uv sync --no-editable
      - run: uv run qgis-plugin-dev-tools build
      - run: uv run qgis-plugin-dev-tools publish dist/*.zip
        env:
          QPDT_PUBLISH_USERNAME: ${{ secrets.QGIS_REPO_USERNAME }}
          QPDT_PUBLISH_PASSWORD: ${{ secrets.QGIS_REPO_PASSWORD }}
      - uses: svenstaro/upload-release-action@2.3.0
        with:
          file: dist/*
          file_glob: true
