name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tag }}
    strategy:
      matrix:
        qgis-image-tag:
          - release-3_22 # ltr
          - release-3_26 # latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - run: |
          python -m venv .venv --system-site-packages
      - run: |
          pip install -r requirements.txt -r requirements.dev --no-deps --only-binary=:all:
      - run: |
          pytest
