name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tags }}
    strategy:
      matrix:
        qgis-image-tags: [release-3_22, release-3_28, release-3_34, 3.40.1]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 -m venv .venv --system-site-packages
      - run: |
          source .venv/bin/activate
          .venv/bin/pip3 install -q -r requirements.txt --no-deps --only-binary=:all:
          .venv/bin/pip3 install . --no-deps
        shell: bash
      - run: |
          source .venv/bin/activate
          .venv/bin/pytest
        shell: bash
        env:
          QT_QPA_PLATFORM: offscreen

  plugin_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      # Use extra pip install . to do a non-editable install,
      # so that .dist-info will go the package instead of .egg-info
      - run: |
          pip install -r requirements.txt --no-deps --only-binary=:all:
          pip install . --no-deps
      - run: |
          qgis-plugin-dev-tools build
      - uses: actions/upload-artifact@v3
        with:
          name: plugin-zip
          path: dist/*.zip
