name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tag }}
    strategy:
      matrix:
        qgis-image-tag:
          - release-3_22 # ltr
          - release-3_26 # latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - run: |
          pip3 install virtualenv && virtualenv .venv --system-site-packages
      # use plain .ins since .txts are compiled for windows & python 3.9
      - run: |
          .venv/bin/pip3 install -r requirements.in -r requirements-dev.in
      - run: |
          .venv/bin/pytest
