name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tags }}
    strategy:
      matrix:
        qgis-image-tags: [release-3_22, release-3_28, release-3_34, "3.44"]
      fail-fast: false

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - run: uv venv .venv --system-site-packages
      - run: uv sync
      - run: .venv/bin/python -m pytest -v
        env:
          QT_QPA_PLATFORM: offscreen

  plugin_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
        with:
          python-version: "3.9"
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      # Use --no-editable so .dist-info is written to site-packages instead of .egg-info
      - run: uv sync --no-editable
      - run: uv run qgis-plugin-dev-tools build
      - uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: dist/*.zip
