name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tag }}
    strategy:
      matrix:
        qgis-image-tag:
          - release-3_22@sha256:a05df35259317e3457d4cdc73f0aabf0623f1e7a8257c56bff10b041ded3dce3
          - release-3_26@sha256:3a7d5654782ca856b4bddcad88d1e5c7562f5a58015876ec6143b89bd77d2791
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - run: |
          pip3 install virtualenv && virtualenv .venv --system-site-packages
      - run: |
          .venv/bin/pip3 install -q -r requirements-ci.txt --no-deps --only-binary=:all:
          .venv/bin/pip3 install . --no-deps
      - run: |
          .venv/bin/pytest
        env:
          QT_QPA_PLATFORM: offscreen

  plugin_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      # Use extra pip install . to do a non-editable install,
      # so that .dist-info will go the package instead of .egg-info
      - run: |
          pip install -r requirements.txt --no-deps --only-binary=:all:
          pip install . --no-deps
      - run: |
          qgis-plugin-dev-tools build
      - uses: actions/upload-artifact@v3
        with:
          name: plugin-zip
          path: dist/*.zip
